export default [
  { name: 'tittibhasana', sound: 'teetibaasina' },
  { name: 'surya bhedana', sound: 'surhreya behdaahna' },
  { name: 'sitali', sound: 'seetaly' },
  { name: 'brahmari', sound: 'braamari' },
  { name: 'kapalabhati', sound: 'kapala baati' },
  { name: 'kapalabhatti', sound: 'kapala baati' },
  { name: 'sivananda', sound: 'shiva naanda' },
  { name: 'vinyasa', sound: 'vin yaasa' },
  { name: 'nauli', sound: 'nowly' },
  { name: 'ujjayi', sound: 'wu jighy' },
  { name: 'uddiyana', sound: 'uedi aana' },
  { name: 'agni sara', sound: 'agni saahra' },
  { name: 'pranayama', sound: 'prana yama' },
  { name: 'astavakrasana', sound: 'aasta vikraasina' },
  { name: 'savasana', sound: 'shavaasina' },
  { name: 'asana', sound: ' aasina' },
  { name: 'eka ', sound: 'ecaa ' },
  { name: 'baddha', sound: 'baada' },
];