export default [
  'baddha konasana',
  'tittibhasana',
  'astavakrasana',
  'eka pada bakasana',
  'virasana',
  // 'savasana',
  // 'chatarunga',
  // 'down dog',
  // 'half moon',
  // 'cobra',
  // 'lounge lizard',
  // 'twisting lunge',
  // 'seated sidebend',
  // 'handstand',
];